{\rtf1\ansi\ansicpg1252\cocoartf2822
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\froman\fcharset0 Times-Roman;}
{\colortbl;\red255\green255\blue255;\red197\green136\blue83;\red155\green162\blue177;\red0\green0\blue0;
}
{\*\expandedcolortbl;;\cssrgb\c81961\c60392\c40000;\cssrgb\c67059\c69804\c74902;\cssrgb\c0\c0\c0;
}
\paperw11900\paperh16840\margl1440\margr1440\vieww28600\viewh18000\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs24 \cf2 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec2 services\cf3 \strokec3 :\cf0 \strokec4  \
   \cf3 \strokec3 -\cf0 \strokec4  \cf2 \strokec2 type\cf3 \strokec3 :\cf0 \strokec4  web  \
     \cf2 \strokec2 name\cf3 \strokec3 :\cf0 \strokec4  instituto\cf3 \strokec3 -\cf0 \strokec4 metaforma \
     \cf2 \strokec2 env\cf3 \strokec3 :\cf0 \strokec4  python \
     \cf2 \strokec2 plan\cf3 \strokec3 :\cf0 \strokec4  free \
     \cf2 \strokec2 buildCommand\cf3 \strokec3 :\cf0 \strokec4  pip install \cf3 \strokec3 -\cf0 \strokec4 r requirements.txt \
     \cf2 \strokec2 startCommand\cf3 \strokec3 :\cf0 \strokec4  streamlit run streamlit_app.py \cf3 \strokec3 --\cf0 \strokec4 server.port $PORT \cf3 \strokec3 --\cf0 \strokec4 server.address 0.0.0.0 \
     \cf2 \strokec2 envVars\cf3 \strokec3 :\cf0 \strokec4  \
     \cf3 \strokec3 -\cf0 \strokec4  \cf2 \strokec2 key\cf3 \strokec3 :\cf0 \strokec4  PYTHON_VERSION \
       \cf2 \strokec2 value\cf3 \strokec3 :\cf0 \strokec4  3.9.16}